baseURL: https://githubuser.github.io
languageCode: en-us
title: Innovitiers Consulting
theme: "PaperMod"
ignoreLogs = ['warning-goldmark-raw-html']

params:
  homeInfoParams:
    Title: Innovitiers Consulting
    Content: Sujeeth  Pakala

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/psujeethkumar"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Sujeeth Pakala"
  contact: "sujeethpakala@innovitiers.com"
  feedlinks: true
  mobileMenu: true

  #Google Analytics 4 optional
  # env: #production
  # GoogleAnalytics: "G-00000XXXXX"
  # sitemap:
  #   changefreq: daily
  #   filename: sitemap.xml
  #   priority: 0.5

# outputs:
#   home:
#     - HTML
#     - RSS
#     - JSON # is necessary
#   section:
#     - HTML
#     - RSS
#     - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
